version: "3"
services:
  backend:
    build:
      context: Nodejs/
    volumes:
      - ./Nodejs/:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      DAPU: "Hello"
  frontend:
    build:
      context: React/
      args:
        - REACT_APP_HOST_IP= "Hello Dac Phuc"
    volumes:
      - ./React/:/app
    ports:
      - "8000:8000"
