version: "3"
services:
  backend:
    stdin_open: true
    build:
      context: Nodejs/
    volumes:
      - ./Nodejs/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    environment:
      DAPU: "Hello"
  frontend:
    stdin_open: true
    build:
      context: frontend/
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    links:
      - backend
    environment:
      REACT_APP_NODE_IP: backend
