version: "3"
services:
  backend:
    build:
      context: Nodejs/
    volumes:
      - ./Nodejs/:/usr/src/app
    ports:
      - "8080:8080"
  frontend:
    build:
      context: React/
    volumes:
      - ./React/:/app
    ports:
      - "8000:8000"
